require("rick.plugins")
require("rick.options")
require("rick.keymaps")
require("rick.lsp")
require("rick.cmp")
require("rick.telescope")
require("rick.toggleterm")
require("rick.autopairs")
require("rick.treesitter")
require("rick.gitsigns")
require("rick.harpoon")
--require("rick.lualine")
--require("rick.bufferline")
-- require("rick.comment")
